dataset:
  name: FB15k-237
  path: ./dataset/fb15k237

model:
  encoder:
    type: RGCN
    hidden_layer_size: 500
    embedding_dim: 500
    dropout: 0.2
    num_bases : 5

  decoder:
    type: DistMult
    l2_penalty_type: schlichtkrull-l2
    l2_penalty : 0.01
  
training:
  epochs: 10000
  sampling:
    negative_sampling_ratio: 3
    edge_dropout: 0.2
  optimiser:
    learning_rate: 0.01
    weight_decay: 0.0001
  evaluation_frequency: 500
  save_frequency: 1000
  early stopping:
    enabled: true
    patience: 10
    delta: 0.001
  load_model: false
  mc_samples: 1
  checkpoint_path: ./checkpoints/FB15k-237_checkpoint_epoch_1000.pth
calibration:
  method: temperature_scaling
  max_iters: 20
  learning_rate: 0.01