dataset:
  name: FB15k-237
  path: ./dataset/fb15k237

model:
  encoder:
    type: RGCN
    hidden_layer_size: 500
    embedding_dim: 500
    dropout: 0.2
    num_bases : 5

  decoder:
    type: DistMult
    l2_penalty : 0.001
    w_gain: false
    b_init: false
  
ensemble:
  enabled: false
  num_models: 5 

training:
  epochs: 10000
  sampling:
    negative_sampling_ratio: 3
    edge_dropout: 0.2
  optimiser:
    learning_rate: 0.01
    weight_decay: 0.0001
  evaluation_frequency: 500
  early stopping:
    enabled: true
    patience: 5
    delta: 0.001
  load_model: false
  save_model: true
  checkpoint_path: ./checkpoints/FB15k-237_checkpoint_epoch_2000.pth
  label_smoothing: 
    positive: 0.95
    negative: 0.05
calibration:
  type: standard
  mc_samples: 5
  method: scalar
  max_iters: 100
  learning_rate: 0.01