dataset:
  name: FB15k-237
  path: ./dataset/fb15k237

model:
  encoder:
    type: RGCN
    hidden_layer_size: 500
    embedding_dim: 500
    dropout: 0.2
    num_bases : 5
    bases_enabled: false

  decoder:
    type: DistMult
    l2_penalty : 0.001
    w_gain: false
    b_init: false
  
ensemble:
  enabled: true
  num_models: 5 

training:
  epochs: 10000
  sampling:
    negative_sampling_ratio: 3
    edge_dropout: 0.2
  optimiser:
    learning_rate: 0.01
    weight_decay: 0
  evaluation_frequency: 500
  early stopping:
    enabled: true
    patience: 5
    delta: 0.001
  load_model: true
  save_model: true
  checkpoint_path: ./new_models/experiment_2/FB15k-237_ensemble_checkpoint_scalar_epoch_1000.pth
  test: true
  label_smoothing: 
    positive: 1
    negative: 0
calibration:
  enabled: true
  type: ensemble
  mc_samples: 5
  method: isotonic_regression
  max_iters: 1000
  learning_rate: 0.01