dataset:
  name: WN18RR
  path: ./dataset/wn18rr

model:
  encoder:
    type: RGCN
    hidden_layer_size: 500
    embedding_dim: 500
    dropout: 0.2
    num_bases : 5

  decoder:
    type: DistMult
    l2_penalty : 0.001
    w_gain: false
    b_init: false
  
training:
  epochs: 10000
  sampling:
    negative_sampling_ratio: 1
    edge_dropout: 0.2
  optimiser:
    learning_rate: 0.01
    weight_decay: 0.0001
  evaluation_frequency: 100
  save_frequency: 50
  early stopping:
    enabled: true
    patience: 10
    delta: 0.001
  load_model: true
  mc_samples: 1
  checkpoint_path: ./checkpoints/WN18RR_checkpoint_best_model_label_smoothing.pth
calibration:
  method: temperature_scaling
  max_iters: 50
  learning_rate: 0.01
